---
version: "3.7"

x-restart-policy:
  &restart-policy
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 30s

x-rollback-config:
  &rollback-config
  rollback_config:
    parallelism: 1
    delay: 30s
    failure_action: continue
    monitor: 60s
    max_failure_ratio: 1
    order: stop-first

x-update-config:
  &update-config
  update_config:
    parallelism: 1
    delay: 30s
    failure_action: pause
    monitor: 60s
    max_failure_ratio: 1
    order: stop-first

networks:

  tomfi_switcher_webapi_net:
    driver: overlay
    labels:
      info.tomfi.schemas.docker.network.name: "Switcher WebAPI network."
      info.tomfi.schemas.docker.network.description: "Use for internal services interacting with the Switcher WebAPI."
    name: tomfi_switcher_webapi_net
    driver_opts:
      com.docker.network.driver.mtu: 1400

services:

  switcher:
    image: tomerfi/switcher_webapi:latest
    init: true
    env_file: env/.env_switcher
    ports:
      - target: 8000
        published: 3698
        protocol: tcp
        mode: host
    networks:
      tomfi_switcher_webapi_net:
    labels:
      info.tomfi.schemas.docker.service.name: "Switcher WebAPI."
      info.tomfi.schemas.docker.service.description: "Web API for controlling the Switcher device."
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      labels:
        info.tomfi.schemas.docker.service.name: "Switcher WebAPI."
        info.tomfi.schemas.docker.service.description: "Web API for controlling the Switcher device."
      placement:
        constraints:
          - node.hostname == docker_station
      <<: *restart-policy
      <<: *rollback-config
      <<: *update-config
    healthcheck:
      test: ["CMD-SHELL", "if [ $$(curl -L -o /dev/null -s -w %{http_code} http://localhost:8000/switcher/get_state) -eq 200 ]; then echo 'healthcheck OK'; exit 0; else echo 'healthcheck ERROR'; exit 1; fi"]
      interval: 15m
      timeout: 10s
      retries: 3
      start_period: 0s
