---
# DO NOT USE THIS DOCKER STACK CONFIGURATION
# HomeAssistant needs to run with host.
# Use the docker-compose orchestration file locally on rpi.

version: '3.7'

x-restart-policy:
  &restart-policy
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 30s

x-rollback-config:
  &rollback-config
  rollback_config:
    parallelism: 1
    delay: 30s
    failure_action: continue
    monitor: 60s
    max_failure_ratio: 1
    order: stop-first

x-update-config:
  &update-config
  update_config:
    parallelism: 1
    delay: 30s
    failure_action: pause
    monitor: 60s
    max_failure_ratio: 1
    order: stop-first

volumes:

  homeassistant_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.104,nolock,soft,rw"
      device: ":/opt/homeassistant"
    labels:
      info.tomfi.schemas.docker.volume.name: "Home-Asistant configuration."
      info.tomfi.schemas.docker.volume.description: "Home-Asistant path for configuration, logs and other files."
      info.tomfi.schemas.docker.volume.driver: "nfs"

  appdaemon_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.104,nolock,soft,rw"
      device: ":/opt/appdaemon"
    labels:
      info.tomfi.schemas.docker.volume.name: "AppDaemon configuration."
      info.tomfi.schemas.docker.volume.description: "Sandboxed python environment for writing automation apps."
      info.tomfi.schemas.docker.volume.driver: "nfs"

networks:

  tomfi_homeautomation_net:
    driver: overlay
    labels:
      info.tomfi.schemas.docker.network.name: "Home assistant network."
      info.tomfi.schemas.docker.network.description: "Use for services required to work with home assisant."
    name: tomfi_homeautomation_net
    driver_opts:
      com.docker.network.driver.mtu: 1400

  tomfi_mosquitto_net:
    external: true

  tomfi_mariadb_net:
    external: true

  tomfi_qbittorrent_net:
    external: true

  tomfi_traccar_net:
    external: true

services:

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.95.4
    init: true
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
        mode: host
      - target: 20002
        published: 20002
        protocol: udp
        mode: host
    volumes:
      - type: volume
        source: homeassistant_config
        target: /config
        volume:
          nocopy: true
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      tomfi_homeautomation_net:
      tomfi_mosquitto_net:
      tomfi_mariadb_net:
      tomfi_qbittorrent_net:
      tomfi_traccar_net:
    labels:
      info.tomfi.schemas.docker.container.name: "Homeassistant rpi3 docker image."
      info.tomfi.schemas.docker.container.description: "Open source home automation."
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      labels:
        info.tomfi.schemas.docker.service.name: "Homeassistant rpi3 docker image."
        info.tomfi.schemas.docker.service.description: "Open source home automation."
      placement:
        constraints:
          - node.hostname == haserver
      <<: *restart-policy
      <<: *rollback-config
      <<: *update-config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 0s

  appdaemon:
    image: <Reducted-Private-Repository>/tomerfi/appdaemon305:rpi_fix
    init: true
    ports:
      - target: 5555
        published: 5555
        protocol: tcp
        mode: host
      - target: 5750
        published: 5750
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: appdaemon_config
        target: /conf
        volume:
          nocopy: true
    networks:
      tomfi_homeautomation_net:
      tomfi_mosquitto_net:
    labels:
      info.tomfi.schemas.docker.container.name: "AppDaemon docker image."
      info.tomfi.schemas.docker.container.description: "Open source home automation robust event driven tool."
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      labels:
        info.tomfi.schemas.docker.service.name: "AppDaemon docker image."
        info.tomfi.schemas.docker.service.description: "Open source home automation robust event driven tool."
      placement:
        constraints:
          - node.hostname == haserver
      <<: *restart-policy
      <<: *rollback-config
      <<: *update-config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 0s
